language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kdaout/docker-react -f Dockerfile.dev .

script:
  - docker run kdaout/docker-react npm run test -- --coverage